version: "3"
services:
  notebook:
    # Dockerfileのイメージを使う
    build: .
    # ポートの設定("ホスト：コンテナ")
    # 8000:8888とするとlocalhost:8000からアクセスできる
    ports:
      - "8000:8888"
    volumes:
      - ./work:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
